-- =============================================================================
-- Migration: Initial Database Schema
-- Created: 2025-10-26 15:52:27 UTC
-- Description: Creates all core tables and indexes for the SQL AI Agent MVP
--
-- Tables Created:
--   - users: User accounts with authentication and role-based access
--   - sessions: Session tracking for authentication with expiration
--   - query_attempts: History of natural language queries and generated SQL
--   - query_results_manifest: Metadata for query results pagination/export
--   - schema_snapshots: Temporal history of PostgreSQL schema cache
--   - kb_examples_index: Index of knowledge base .sql example files
--   - metrics_rollup: Weekly aggregated metrics for basic analytics
--
-- Security Note:
--   Row-level security must be enforced at the application layer.
--   SQLite does not support native RLS. The application must filter
--   query results by user_id for non-admin users.
-- =============================================================================

-- Enable foreign key constraints for referential integrity
-- SQLite disables foreign keys by default, so we explicitly enable them
pragma foreign_keys = on;

-- =============================================================================
-- Table: users
-- Purpose: Store user accounts with authentication credentials and roles
-- Security: Store bcrypt password hashes only, never plaintext passwords
-- =============================================================================
create table users (
    -- Primary key with auto-increment for user identification
    id integer primary key autoincrement not null,
    
    -- Unique username for login, enforced at DB level
    username text not null unique,
    
    -- Bcrypt password hash for authentication
    password_hash text not null,
    
    -- Role-based access control: 'admin' can view all data, 'user' sees only own data
    role text not null check (role in ('admin', 'user')),
    
    -- Soft-delete flag: 0=inactive, 1=active
    -- Allows disabling accounts without losing historical data
    active integer not null default 1 check (active in (0, 1)),
    
    -- Timestamp of account creation in ISO 8601 format
    created_at text not null default (datetime('now'))
);

-- Unique index on username for fast login lookups and uniqueness enforcement
create unique index idx_users_username on users(username);

-- =============================================================================
-- Table: sessions
-- Purpose: Track active user sessions with 8-hour expiration
-- Security: Supports secure session management with revocation capability
-- =============================================================================
create table sessions (
    -- Primary key with auto-increment for session identification
    id integer primary key autoincrement not null,
    
    -- Foreign key to users table with cascade delete
    -- When a user is deleted, all their sessions are automatically removed
    user_id integer not null references users(id) on delete cascade,
    
    -- Unique session token (JWT or secure random string)
    token text not null unique,
    
    -- Timestamp when session was created
    created_at text not null default (datetime('now')),
    
    -- Session expiration timestamp (8 hours from creation)
    -- Application should validate this before accepting the session
    expires_at text not null,
    
    -- Revocation flag: 0=active, 1=revoked
    -- Allows manual logout by setting revoked=1
    revoked integer not null default 0 check (revoked in (0, 1))
);

-- Unique index on token for fast session lookups and uniqueness enforcement
create unique index idx_sessions_token on sessions(token);

-- Composite index for efficient session validation queries
-- Allows fast lookup of active sessions for a user
create index idx_sessions_user_expires on sessions(user_id, expires_at);

-- =============================================================================
-- Table: query_attempts
-- Purpose: Audit log of all natural language queries and their execution
-- History: Preserves complete history for analysis and retry functionality
-- =============================================================================
create table query_attempts (
    -- Primary key with auto-increment for attempt identification
    id integer primary key autoincrement not null,
    
    -- Foreign key to users with restrict delete
    -- Prevents user deletion if they have query history (audit preservation)
    user_id integer not null references users(id) on delete restrict,
    
    -- Original natural language query from the user
    natural_language_query text not null,
    
    -- SQL generated by the LLM (may be null if generation failed)
    generated_sql text,
    
    -- Execution status: tracks the complete lifecycle of a query
    -- - not_executed: SQL generated but not yet run
    -- - failed_generation: LLM failed to generate valid SQL
    -- - failed_execution: SQL generated but execution failed
    -- - success: Query executed successfully
    -- - timeout: Query exceeded execution time limit
    status text not null check (status in ('not_executed', 'failed_generation', 'failed_execution', 'success', 'timeout')),
    
    -- Timestamp when user submitted the natural language query
    created_at text not null default (datetime('now')),
    
    -- Timestamp when SQL was successfully generated (null if generation failed)
    generated_at text,
    
    -- Timestamp when SQL was executed (null if not executed)
    executed_at text,
    
    -- Time in milliseconds for SQL generation (for performance monitoring)
    generation_ms integer,
    
    -- Time in milliseconds for SQL execution (for performance monitoring)
    execution_ms integer,
    
    -- Optional self-reference for retry/re-run lineage
    -- Links to the original attempt if this is a retry
    -- Null for original attempts, set null on delete of referenced attempt
    original_attempt_id integer references query_attempts(id) on delete set null
);

-- Composite index for user's query history (most recent first)
-- Optimizes the main history view for each user
create index idx_query_attempts_user_created on query_attempts(user_id, created_at desc);

-- Composite index for status-based queries (most recent first)
-- Enables efficient filtering by success/failure status
create index idx_query_attempts_status_created on query_attempts(status, created_at desc);

-- Index for retry lineage queries
-- Allows efficient lookup of all retries for a given original attempt
create index idx_query_attempts_original on query_attempts(original_attempt_id);

-- =============================================================================
-- Table: query_results_manifest
-- Purpose: Metadata for query results pagination and CSV export
-- Note: Actual result rows are NOT stored in SQLite to keep database small
-- =============================================================================
create table query_results_manifest (
    -- Primary key is the attempt_id (1-to-1 relationship)
    -- This ensures exactly one manifest per query attempt
    attempt_id integer primary key not null references query_attempts(id) on delete cascade,
    
    -- Total number of rows returned by the query
    total_rows integer,
    
    -- Number of rows per page for UI pagination
    page_size integer not null default 500,
    
    -- Total number of pages (calculated from total_rows / page_size)
    page_count integer,
    
    -- Maximum rows allowed in CSV export
    export_row_limit integer not null default 10000,
    
    -- Flag indicating if export was truncated: 0=complete, 1=truncated
    export_truncated integer not null default 0 check (export_truncated in (0, 1)),
    
    -- File path to the CSV export file (null if not yet exported)
    export_file_path text,
    
    -- Timestamp when manifest was created
    created_at text not null default (datetime('now'))
);

-- No additional indexes needed: primary key on attempt_id covers all lookups

-- =============================================================================
-- Table: schema_snapshots
-- Purpose: Temporal history of PostgreSQL schema cache for audit and refresh
-- Standalone: No foreign keys, maintains independent schema history
-- =============================================================================
create table schema_snapshots (
    -- Primary key with auto-increment for snapshot identification
    id integer primary key autoincrement not null,
    
    -- Timestamp when schema was loaded/cached
    loaded_at text not null default (datetime('now')),
    
    -- Hash of the source schema for change detection
    -- Allows quick comparison to detect schema changes
    source_hash text not null,
    
    -- Count of tables in the schema snapshot
    table_count integer not null,
    
    -- Total count of columns across all tables
    column_count integer not null,
    
    -- Complete schema definition as JSON
    -- Stores table names, column names, types, and relationships
    tables_json text not null
);

-- Index for temporal queries (most recent first)
-- Enables efficient retrieval of the latest schema snapshot
create index idx_schema_snapshots_loaded_at on schema_snapshots(loaded_at desc);

-- Unique index on source_hash to prevent duplicate snapshots
-- Ensures we only store one snapshot per unique schema state
create unique index idx_schema_snapshots_source_hash on schema_snapshots(source_hash);

-- =============================================================================
-- Table: kb_examples_index
-- Purpose: Index of knowledge base .sql example files for semantic search
-- Standalone: No foreign keys, maps on-disk files to searchable metadata
-- =============================================================================
create table kb_examples_index (
    -- Primary key with auto-increment for example identification
    id integer primary key autoincrement not null,
    
    -- Path to the .sql example file on disk
    -- Unique constraint ensures each file is indexed only once
    file_path text not null unique,
    
    -- Natural language question that the example demonstrates
    question_text text not null,
    
    -- Optional comma-separated tags for categorization
    -- Examples: 'joins', 'aggregation', 'subquery', etc.
    tags text,
    
    -- Timestamp of last load/refresh from disk
    last_loaded_at text not null default (datetime('now')),
    
    -- Optional embedding vector stored as BLOB
    -- Used for semantic similarity search (cosine distance)
    -- May be null if embeddings are cached in memory only
    embedding blob
);

-- Unique index on file_path for fast lookups and uniqueness enforcement
create unique index idx_kb_examples_file_path on kb_examples_index(file_path);

-- Index on tags for category-based filtering
-- Enables queries like "show me all examples tagged 'joins'"
create index idx_kb_examples_tags on kb_examples_index(tags);

-- Index for temporal queries (most recent first)
-- Useful for identifying stale examples that need refresh
create index idx_kb_examples_loaded_at on kb_examples_index(last_loaded_at desc);

-- =============================================================================
-- Table: metrics_rollup
-- Purpose: Weekly aggregated metrics for basic success rate analytics
-- Optional: Provides lightweight metrics without heavy analytics infrastructure
-- =============================================================================
create table metrics_rollup (
    -- Primary key with auto-increment for rollup identification
    id integer primary key autoincrement not null,
    
    -- ISO 8601 date of the week start (Monday)
    -- Example: '2025-10-20' for the week starting October 20
    week_start text not null,
    
    -- Optional foreign key to users for per-user metrics
    -- Null for system-wide rollups, set null on user deletion
    user_id integer references users(id) on delete cascade,
    
    -- Total number of query attempts in this week
    attempts_count integer not null default 0,
    
    -- Number of queries that were executed (success or failed execution)
    executed_count integer not null default 0,
    
    -- Number of successfully executed queries
    success_count integer not null default 0
);

-- Composite index for weekly metrics queries
-- Enables efficient lookup of metrics by week and optional user filtering
create index idx_metrics_week_user on metrics_rollup(week_start, user_id);

-- =============================================================================
-- Migration Complete
-- =============================================================================