/**
 * Auto-generated TypeScript types from SQLite database schema
 * Generated by: scripts/generate_types.py
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * To regenerate: make generate-types
 */

// Table: kb_examples_index
export interface KbExamplesIndex {
  /** Primary key */
  id: number;
  file_path: string;
  question_text: string;
  tags?: string | null;
  /** ISO 8601 timestamp */
  last_loaded_at: string;
  embedding?: Uint8Array | null;
}

// Table: metrics_rollup
export interface MetricsRollup {
  /** Primary key */
  id: number;
  week_start: string;
  /** Foreign key reference */
  user_id?: number | null;
  attempts_count: number;
  executed_count: number;
  success_count: number;
}

// Table: query_attempts
export interface QueryAttempts {
  /** Primary key */
  id: number;
  /** Foreign key reference */
  user_id: number;
  natural_language_query: string;
  generated_sql?: string | null;
  status: string;
  /** ISO 8601 timestamp */
  created_at: string;
  /** ISO 8601 timestamp */
  generated_at?: string | null;
  /** ISO 8601 timestamp */
  executed_at?: string | null;
  generation_ms?: number | null;
  execution_ms?: number | null;
  /** Foreign key reference */
  original_attempt_id?: number | null;
}

// Table: query_results_manifest
export interface QueryResultsManifest {
  /** Primary key */
  attempt_id: number;
  total_rows?: number | null;
  page_size: number;
  page_count?: number | null;
  export_row_limit: number;
  export_truncated: number;
  export_file_path?: string | null;
  /** ISO 8601 timestamp */
  created_at: string;
}

// Table: schema_migrations
export interface SchemaMigrations {
  /** Primary key */
  id?: number | null;
  version: string;
  name: string;
  /** ISO 8601 timestamp */
  applied_at: string;
}

// Table: schema_snapshots
export interface SchemaSnapshots {
  /** Primary key */
  id: number;
  /** ISO 8601 timestamp */
  loaded_at: string;
  source_hash: string;
  table_count: number;
  column_count: number;
  tables_json: string;
}

// Table: sessions
export interface Sessions {
  /** Primary key */
  id: number;
  /** Foreign key reference */
  user_id: number;
  token: string;
  /** ISO 8601 timestamp */
  created_at: string;
  /** ISO 8601 timestamp */
  expires_at: string;
  revoked: number;
}

// Table: users
export interface Users {
  /** Primary key */
  id: number;
  username: string;
  password_hash: string;
  role: string;
  active: number;
  /** ISO 8601 timestamp */
  created_at: string;
}

// Utility Types

/** ID type for all primary keys */
export type ID = number;

/** Timestamp string in ISO 8601 format */
export type Timestamp = string;

/** Role types for users */
export type UserRole = 'admin' | 'user';

/** Query attempt status types */
export type QueryStatus = 'not_executed' | 'failed_generation' | 'failed_execution' | 'success' | 'timeout';
